env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
dockers:
  - image_templates:
    - "push.soh.re/servmon:{{ .Tag }}"
    - "push.soh.re/servmon:latest"
    extra_files:
    - template.html
archives:
- name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
  format_overrides:
  - goos: windows
    format: zip
nfpms:
- file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  homepage:  https://github.com/Jmainguy/servmon
  description: A service monitor written in go
  maintainer: Jonathan Seth Mainguy <jon@soh.re>
  license: GPLv2
  vendor: Jmainguy
  release: 1
  replacements:
    amd64: x86_64
  overrides:
      rpm:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}-{{.Release}}.{{ .Arch }}"
      deb:
        file_name_template: "{{ .ProjectName }}_{{ .Version }}-{{.Release}}_{{ .Arch }}"
  formats:
  - deb
  - rpm

brews:
  - tap:
      owner: Jmainguy
      name: homebrew-tap
    folder: Formula
    homepage: https://github.com/Jmainguy/servmon
    description: A service monitor written in go
    license: "GPL-2.0"
    commit_author:
      name: Jonathan Seth Mainguy
      email: jon@soh.re
    test: |
      system "#{bin}/servmon"
    install: |
      bin.install "servmon"

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
